name: Benchmark

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write
  pull-requests: write
  
jobs:
  benchmark:
    runs-on: linux-benchmark
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Prepare
        run: |
          go get go.sia.tech/hostd@master
          go get go.sia.tech/renterd@dev
          go mod tidy

          mkdir -p results
          CGO_ENABLED=1 go build -o bin/ -trimpath -a ./cmd/benchmark
          git reset --hard 
      - name: Run
        run: ./bin/benchmark -output results
      - name: Add Result
        uses: peter-evans/create-pull-request@v7
        id: result
        with:
          delete-branch: true
          commit-message: Add benchmark results
          title: Add benchmark results
          branch: benchmark-result
          labels: |
            benchmark
          add-paths: |
            results/*.csv
      - name: Automerge
        run: gh pr merge --merge --auto "${{ steps.result.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
        
          
      